apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    color: blue   # Start with BLUE version active
  ports:
  - port: 80
    targetPort: 80

